--RÚT TIỀN
CREATE 
--ALTER
PROC USP_RUTTIEN
	@MATK VARCHAR(12),
	@SOTIENRUT FLOAT
AS
BEGIN TRAN
	DECLARE @SODU FLOAT = (SELECT SODU
							FROM TAIKHOAN 
							WHERE MATK = @MATK)
	WAITFOR DELAY '0:0:05'
	IF (@SODU > @SOTIENRUT)
	BEGIN
		SET @SODU = @SODU - @SOTIENRUT
	END
		ELSE
	BEGIN
		PRINT N'SỐ TIỀN KO ĐỦ RÚT'
		ROLLBACK TRAN
		RETURN
	END
	BEGIN TRY
		UPDATE TAIKHOAN
		SET SODU = @SODU
		WHERE MATK = @MATK
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'sỐ DƯ MỚI : ' + CAST(@SODU AS CHAR(10))
	PRINT N'RÚT TIỀN THÀNH CÔNG'
COMMIT TRAN
GO
--GỬI TIỀN VÀO TÀI KHOẢN
CREATE 
--ALTER
PROC USP_GUITIEN
	@MATK VARCHAR(12),
	@SOTIENGUI FLOAT
AS
BEGIN TRAN
	DECLARE @SODU FLOAT = (SELECT SODU
							FROM TAIKHOAN 
							WHERE MATK = @MATK)
	print @sodu
	IF (@SODU <> 0 )
	BEGIN
		SET @SODU = @SODU + @SOTIENGUI
		PRINT @SODU
	END
	WAITFOR DELAY '0:0:05'
	BEGIN TRY
		UPDATE TAIKHOAN
		SET SODU = @SODU
		WHERE MATK = @MATK
	END TRY
	BEGIN CATCH 
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH
	PRINT N'sỐ DƯ MỚI : ' + CAST(@SODU AS CHAR(10))
	PRINT N'GỬI TIỀN THÀNH CÔNG'
COMMIT TRAN