CREATE 
--ALTER
PROC USP_CAU10
	@MaGD INT,
	@MaTK CHAR(12),
	@SoTien FLOAT,
	@NgayGio DATETIME,
	@GhiChu CHAR(40)
AS
BEGIN TRAN
	BEGIN TRY
	IF EXISTS (SELECT * 
				FROM GiaoDich 
				WHERE MaGD = @MaGD )
	BEGIN
		PRINT CAST(@MaGD AS VARCHAR(3)) + N' Đã Tồn Tại'
		ROLLBACK TRAN
		RETURN 1
	END
	IF @SoTien = 0 
	BEGIN
		PRINT N'Số Tiền Phải Khác Không'
		ROLLBACK TRAN
		RETURN 1
	END
	DECLARE @SoDu INT
	SET @SoDu = (SELECT SoDu 
				FROM TaiKhoan 
				WHERE MaTK = @MaTK)
	IF @SoDu + @SoTien <= 0
	BEGIN
		PRINT N'Số Tiền Không Còn Đủ Để Giao Dịch'
		ROLLBACK TRAN
		RETURN 1
	END
	INSERT GIAODICH
	VALUES(@MAGD, @MATK,@SOTIEN, @NgayGio,@GHICHU)
	UPDATE TAIKHOAN
	SET SODU = SODU + @SoTien
	WHERE MATK = @MATK
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN 1	
	END CATCH
COMMIT TRAN
RETURN 0
GO
CREATE --ALTERPROC USP_CAU3	@MATK CHAR(12)ASSET TRAN ISOLATION LEVEL REPEATABLE READBEGIN TRAN	BEGIN TRY		IF NOT EXISTS (SELECT *						FROM TAIKHOAN						WHERE MATK = @MATK)		BEGIN			PRINT  @MATK + N' KHÔNG TỒN TẠI'			ROLLBACK TRAN			RETURN 1		END		IF EXISTS (SELECT *				FROM GIAODICH				WHERE MATK = @MATK)		BEGIN			PRINT  @MATK + N' ĐÃ THỰC HIỆN GIAO DỊCH, KHÔNG XÓA ĐƯỢC'			ROLLBACK TRAN			RETURN 1		END		--ĐỂ TEST		WAITFOR DELAY '0:0:05'		---------------------------------		DELETE TAIKHOAN		WHERE MATK = @MATK	END TRY	BEGIN CATCH		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN 1	END CATCHCOMMIT TRANRETURN 0