CREATE 
--ALTER
PROC USP_CAU10
	@MaGD INT,
	@MaTK CHAR(12),
	@SoTien FLOAT,
	@NgayGio DATETIME,
	@GhiChu CHAR(40)
AS
--SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
	IF EXISTS (SELECT * 
				FROM GiaoDich 
				WHERE MaGD = @MaGD )
	BEGIN
		PRINT CAST(@MaGD AS VARCHAR(3)) + N' Đã Tồn Tại'
		ROLLBACK TRAN
		RETURN 1
	END
	IF @SoTien = 0 
	BEGIN
		PRINT N'Số Tiền Phải Khác Không'
		ROLLBACK TRAN
		RETURN 1
	END
	DECLARE @SoDu FLOAT
	SET @SoDu = (SELECT SoDu 
				FROM TaiKhoan 
				WHERE MaTK = @MaTK)
	IF @SoDu + @SoTien <= 0
	BEGIN
		PRINT N'Số Tiền Không Còn Đủ Để Giao Dịch'
		ROLLBACK TRAN
		RETURN 1
	END
	--ĐỂ TEST
	WAITFOR DELAY '0:0:05'
	-------------
	
	UPDATE TAIKHOAN
	SET SODU = SODU + @SoTien
	WHERE MATK = @MATK
	INSERT GIAODICH
	VALUES(@MAGD, @MATK,@SOTIEN, @NgayGio,@GHICHU)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN 1	
	END CATCH
COMMIT TRAN
RETURN 0
GO
CREATE --ALTERPROC USP_CAU4	@MATK CHAR(12),	@NGAYLAP DATETIME,	@SODU FLOAT,	@TRANGTHAI NCHAR(10)ASBEGIN TRAN	BEGIN TRY		IF NOT EXISTS(SELECT *					FROM TAIKHOAN					WHERE MATK = @MATK)		BEGIN			PRINT @MATK +N' KHÔNG TỒN TẠI'			ROLLBACK TRAN			RETURN 1		END		IF @NGAYLAP IS NULL		BEGIN			PRINT N'NGÀY LẬP KHÔNG ĐƯỢC TRỐNG'			ROLLBACK TRAN			RETURN 1		END		IF @SODU <100000		BEGIN			PRINT N'SỐ DƯ KHÔNG HỢP LỆ'			ROLLBACK TRAN			RETURN 1		END		IF @TRANGTHAI NOT IN (N'ĐANG DÙNG',N'ĐÃ KHÓA', N'BỊ HỦY')		BEGIN			PRINT N'TÌNH TRẠNG KHÔNG HỢP LỆ'			ROLLBACK TRAN			RETURN 1		END		UPDATE TAIKHOAN		SET NGAYLAP = @NGAYLAP,			SODU = @SODU,			TINHTRANG = @TRANGTHAI		WHERE MATK = @MATK 	END TRY	BEGIN CATCH		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN 1	END CATCHCOMMIT TRANRETURN 0